* Tasks
** Goals
*** Set  a goal to be a millionaire: Why? FOR WHAT it will MAKE of you to achieve IT.
*** Set the kind of goals that will make something of you to achieve them.
*** What am I becoming here?
*** It's what you become that makes you valuable.
*** Dont set your goals too low.
*** Don't compromise, don't sell out.
**** Questons:
***** What do I want within the next one to ten years 
****** 50 things/long range goals
******* what do i want to do, be, see, have, go, share
******* no detail, write fast
******* 12 to 15 minutes on this.
***** Write next to the thing i think it will take 1 year to accomplish, write a 1, 3 years write a 3, 10 years write a 10.
****** list economic goals, material items I want, goals for personal devlopment(health, etc..) 
****** go back to list, pick out most important 1 3 5 10 year goals.
****** write down: describe each goal, 1 paragraph. Why is it importnt? Talk myself into it? talk myself out of it? Aproximately 4 goals for 1, 3, 5, 10. 
***** Short range goals.
****** All the little things I would like to have or accomplish within the next year.
****** Every week check off at least one thing on my list of goals.
* Miscellaneous
#+STARTUP: hidestars
